#!/bin/sh /etc/rc.common

START=90
STOP=89
USE_PROCD=1

start_service() {
	mkdir -p /run/dedalo/
	procd_open_instance "dedalo"
	procd_set_param command /usr/sbin/chilli
	procd_set_param file "/opt/icaro/dedalo/chilli.conf"
	procd_append_param command -c /opt/icaro/dedalo/chilli.conf --fg
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}

stop_service() {
	if [ -d "/run/dedalo/" ]; then
		rm -rf /run/dedalo/
	fi
}
